# Generated by Django 6.0.5 on 2026-05-10 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiverSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_length_km', models.FloatField(help_text='Total river length in km')),
                ('base_flow_rate', models.FloatField(help_text='Base flow rate m³/s')),
                ('sinuosity_index', models.FloatField(default=1.3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'River System',
            },
        ),
        migrations.CreateModel(
            name='MonitoringStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('station_code', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('upstream_reference', 'Upstream Reference'), ('industrial_outfall', 'Industrial Outfall Zone'), ('agricultural_buffer', 'Agricultural Buffer Zone'), ('municipal_intake', 'Municipal Water Intake'), ('wetland_buffer', 'Wetland Buffer'), ('downstream_gauge', 'Downstream Gauge'), ('custom', 'Custom')], max_length=30)),
                ('km_location', models.FloatField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('alert_threshold_heavy_metals', models.FloatField(blank=True, null=True)),
                ('alert_threshold_organics', models.FloatField(blank=True, null=True)),
                ('alert_threshold_nutrients', models.FloatField(blank=True, null=True)),
                ('alert_threshold_pathogens', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('river', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_stations', to='river.riversystem')),
            ],
            options={
                'ordering': ['km_location'],
            },
        ),
        migrations.CreateModel(
            name='ContaminantSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_label', models.CharField(max_length=100)),
                ('contaminant_type', models.CharField(choices=[('heavy_metals', 'Heavy Metals'), ('organic', 'Organic Compounds'), ('nutrients', 'Nutrients'), ('pathogens', 'Pathogens'), ('suspended_solids', 'Suspended Solids'), ('other', 'Other')], max_length=30)),
                ('km_location', models.FloatField()),
                ('plume_sigma_x', models.FloatField(default=5.0)),
                ('plume_sigma_y', models.FloatField(default=2.0)),
                ('peak_concentration', models.FloatField()),
                ('decay_rate', models.FloatField()),
                ('discharge_mode', models.CharField(choices=[('continuous', 'Continuous'), ('pulsed', 'Pulsed'), ('batch', 'Batch')], default='continuous', max_length=20)),
                ('pulse_on_hours', models.FloatField(blank=True, null=True)),
                ('pulse_off_hours', models.FloatField(blank=True, null=True)),
                ('flow_rate_m3s', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('river', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contaminant_sources', to='river.riversystem')),
            ],
            options={
                'ordering': ['km_location'],
            },
        ),
        migrations.CreateModel(
            name='CrossSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_marker', models.FloatField()),
                ('section_type', models.CharField(choices=[('pool', 'Pool'), ('riffle', 'Riffle'), ('run', 'Run'), ('glide', 'Glide')], max_length=20)),
                ('width_m', models.FloatField()),
                ('max_depth_m', models.FloatField()),
                ('bank_height_m', models.FloatField()),
                ('thalweg_offset_m', models.FloatField(default=0.0)),
                ('parabola_a', models.FloatField()),
                ('parabola_b', models.FloatField()),
                ('river', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_sections', to='river.riversystem')),
            ],
            options={
                'ordering': ['km_marker'],
                'unique_together': {('river', 'km_marker')},
            },
        ),
    ]
