# Generated by Django 6.0.5 on 2026-05-10 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('river', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_timestamp', models.DateTimeField(help_text='Timestamp from the sensor device')),
                ('heavy_metals_mgl', models.FloatField(blank=True, null=True)),
                ('organics_mgl', models.FloatField(blank=True, null=True)),
                ('nutrients_mgl', models.FloatField(blank=True, null=True)),
                ('pathogens_cfu', models.FloatField(blank=True, help_text='CFU/100mL', null=True)),
                ('suspended_solids_mgl', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('dissolved_oxygen_mgl', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('turbidity_ntu', models.FloatField(blank=True, null=True)),
                ('conductivity_us', models.FloatField(blank=True, help_text='μS/cm', null=True)),
                ('flow_rate_m3s', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('battery_level_pct', models.FloatField(blank=True, null=True)),
                ('signal_strength_dbm', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('alert', 'Alert'), ('critical', 'Critical'), ('error', 'Error')], default='ok', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(default=dict, help_text='Full raw JSON from sensor')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='river.monitoringstation')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contaminant_type', models.CharField(choices=[('heavy_metals', 'Heavy Metals'), ('organics', 'Organics'), ('nutrients', 'Nutrients'), ('pathogens', 'Pathogens'), ('other', 'Other')], max_length=30)),
                ('measured_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], max_length=20)),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='river.monitoringstation')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensorreading')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Payload sent to the simulation engine')),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='sensors.alertevent')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['station', '-received_at'], name='sensors_sen_station_33489d_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['status'], name='sensors_sen_status_c719c7_idx'),
        ),
    ]
